### ISSUE TITLE
Onboarding, Information Request

### ISSUE THREAD

**Issue by viviloaf** [tazz4843/McPy#62]
Coming onto the project, documentation is currently lacking.

I was told an accessible resource was @Geolykt who at one point did develop for a time.

I'm working through understanding the existing code base and with `WorldGenerator.py`. 

The Pull requests and commit statements suggest that world generation has been executed before concurrently with development, but I can't find any example of a `main.py` which executed any of the functions inside of `WorldGenerator`

@Geolykt , are you able to provide any information? I do know you are not active on this project anymore.

**Comment by hydrostaticcog** [comment]
I have walked @vnguye34 through as much as I could, as most of the code was written before I showed up (mid-September is when I became active). I don't know a whole lot about the older code, and @vnguye34 has questions about that code that I can't answer.

**Comment by Geolykt** [comment]
A LOT of the code currently is pseudocode, with the World generation and most things attached to it being entirely pseudocode.
But no, the code never worked

(closing this since I think this thread is no longer needed)
