### ISSUE TITLE
Not logging chat message

### ISSUE THREAD

**Issue by oshaulz** [tazz4843/McPy#72]
**Bug Description**
Chat is not being logged by logging import

**To Reproduce**
1. Send Text in Minecraft
2. No logging for message

**Expected behaviour**
As in the code `logging.info(message)` in Connection.py its expected to be logged as info

**Host system:**
 - MacOS
 - Big Sur (X86)
 - Python 3.8.5 64-bit

**Comment by Geolykt** [comment]
Cannot reproduce on my side where I am getting "[2021-05-07 21:23:50,708 - INFO - NETWORK_THREAD] \<emeric987\> tt" as intended. Could be yet another OS-dependent bug (what's wrong with you python?)

**Comment by hydrostaticcog** [comment]
Great, more Mac errors. I will attempt to reproduce this bug soon, when u have access to my Mac.

**Comment by oshaulz** [comment]
I found a explanation to this issue:
[https://docs.python.org/3/howto/logging.html#a-simple-example]()
Example of this issue:
`import logging
logging.warning('Watch out!')  # will print a message to the console
logging.info('I told you so')  # will not print anything `

**Comment by Geolykt** [comment]
> I found a explanation to this issue:
> https://docs.python.org/3/howto/logging.html#a-simple-example
> Example of this issue:
> `import logging logging.warning('Watch out!') # will print a message to the console logging.info('I told you so') # will not print anything `

We are setting the log level in https://github.com/mcpyproject/McPy/blob/master/classes/mcPy/McPy.py#L57-L58 though. Though could you try to run the server with "--debug" to see if it works

**Comment by hydrostaticcog** [comment]
I can confirm that this bug does not seem to exist on Ubuntu Linux 20.04.2 LTS (Kernel 5.4).

**Comment by hydrostaticcog** [comment]
I can also confirm this bug on MacOS 10.10.5 (Yosemite)

**Comment by ntoskrnl4** [comment]
ah fun, another MacOS one it seems. Can you try setting a breakpoint inside the program and checking the log level there? Just to make sure it didn't change out from under us

**Comment by hydrostaticcog** [comment]
Issue identified: if the `debug` option is not passed, it sets an empty logging format. I am creating a PR to resolve this now.

**Comment by hydrostaticcog** [comment]
Resolved by #73
